name: wave_widget
description: Wave Widget â€” Beautiful animated waves for Flutter
version: 0.1.1
homepage: https://github.com/vanvixi/wave_widget.flutter
repository: https://github.com/vanvixi/wave_widget.flutter
issue_tracker: https://github.com/vanvixi/wave_widget.flutter

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

topics:
  - animation
  - ui
  - wave
  - flutter-wave
  - visualizer

screenshots:
  - description: "WavesWidget demo"
    path: assets/demo.webp